type SampleOpportunity = {
  id: string;
  businessName: string;
  website: string;
  location: string;
  industry: string;
  contactName: string;
  contactRole: string;
  contactEmail: string;
  emailConfidence: string;
  emailSourceUrl: string;
  fit: string;
  score: number;
  status: string;
  signalType: string;
  signalSummary: string;
  observation: string;
  inference: string;
  offerTitle: string;
  offerScope: string;
  priceRange: string;
  deliveryTime: string;
  previewIdea: string;
  subject: string;
  emailBody: string;
  reviewerNote: string;
  sourceUrls: string;
  approvedAt: string | null;
  sentAt: string | null;
  repliedAt: string | null;
  nextFollowUpAt: string | null;
};

const sent = "2026-09-15T21:30:00Z";
const followUp = "2026-09-25T16:00:00Z";

export const sampleOpportunities: SampleOpportunity[] = [
  {
    id: "sweet-smiling",
    businessName: "Sweet Smiling Landscapes",
    website: "https://www.sweetsmilinglandscapes.com",
    location: "Ventura County, CA",
    industry: "Regenerative landscape design",
    contactName: "Natasha Elliott",
    contactRole: "Founder / landscape professional",
    contactEmail: "sweetsmilinglandscapes@gmail.com",
    emailConfidence: "HIGH",
    emailSourceUrl: "https://www.sweetsmilinglandscapes.com/get-in-touch",
    fit: "BEST FIT",
    score: 94,
    status: "replied",
    signalType: "Customer education",
    signalSummary: "A highly visual, education-led service where rebate complexity can become a qualified lead tool.",
    observation: "The business emphasizes regenerative lawn conversion and water-conscious garden design.",
    inference: "A homeowner-facing rebate and water-savings calculator could turn education into a clearer consultation path.",
    offerTitle: "Lawn conversion lead calculator",
    offerScope: "Branded calculator, service-area logic, lead form, email handoff and mobile QA.",
    priceRange: "$750–$1,200",
    deliveryTime: "5–7 days",
    previewIdea: "A single-screen calculator using lawn size and district to estimate rebate and water savings.",
    subject: "a rebate calculator in your voice",
    emailBody: "Hi Natasha,\n\nI was looking at the way Sweet Smiling explains regenerative lawn conversion. There is a lot for a homeowner to understand before they feel ready to book.\n\nSo I made a small calculator that turns lawn size and district into a rough rebate and water-savings estimate, then guides the right people toward a consultation.\n\nIf it feels useful, I can turn it into a real branded version for your site. If not, all good — keep the idea.\n\nPaul\n\nP.S. If you would rather I do not follow up, reply no and I will not.",
    reviewerNote: "Positive reply received. Move to discovery call and proposal; do not send another cold follow-up.",
    sourceUrls: JSON.stringify(["https://www.sweetsmilinglandscapes.com", "https://www.sweetsmilinglandscapes.com/get-in-touch"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: "2026-09-15T21:49:00Z",
    nextFollowUpAt: null,
  },
  {
    id: "plowboy",
    businessName: "Plowboy Landscapes",
    website: "https://plowboylandscapes.com",
    location: "Ventura, CA",
    industry: "Commercial landscape maintenance",
    contactName: "Doug Wasson",
    contactRole: "Owner",
    contactEmail: "office@plowboylandscapes.com",
    emailConfidence: "HIGH",
    emailSourceUrl: "https://plowboylandscapes.com/contact-us",
    fit: "BEST FIT",
    score: 92,
    status: "sent",
    signalType: "Reporting workload",
    signalSummary: "The company publicly promises monthly written reports across a large maintenance operation.",
    observation: "Plowboy promotes monthly written client reports and operates with a large field team.",
    inference: "Daily crew activity likely has to be assembled into client-facing reports, creating a repeatable workflow opportunity.",
    offerTitle: "Monthly report that writes itself",
    offerScope: "Crew visit log, photo capture, property history and monthly report export.",
    priceRange: "$1,200–$2,500",
    deliveryTime: "10–14 days",
    previewIdea: "One property visit flowing automatically into a monthly HOA report.",
    subject: "an idea for Plowboy's monthly reports",
    emailBody: "Hi Doug,\n\nI noticed Plowboy promises monthly written reports across a large maintenance operation. That is a strong client service, but every report begins with information coming from the field.\n\nI built a working concept where each property visit creates its own history and the monthly report is generated from that record.\n\nIf the workflow is close to how your team operates, I can build a real version around your process. If not, no problem.\n\nPaul",
    reviewerNote: "Initial email sent. Await reply before changing the offer.",
    sourceUrls: JSON.stringify(["https://plowboylandscapes.com", "https://plowboylandscapes.com/contact-us"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: null,
    nextFollowUpAt: followUp,
  },
  {
    id: "mar-lawn",
    businessName: "Mar Lawn & Landscape",
    website: "https://marlandscape.com",
    location: "Ojai, CA",
    industry: "Landscape construction & maintenance",
    contactName: "Abel Carranza",
    contactRole: "President",
    contactEmail: "admin@marlandscape.com",
    emailConfidence: "HIGH",
    emailSourceUrl: "https://marlandscape.com",
    fit: "BEST FIT",
    score: 90,
    status: "sent",
    signalType: "Proof trapped in testimonials",
    signalSummary: "A client testimonial reports roughly 30% lower water use after an irrigation upgrade.",
    observation: "The company has a measurable water-savings result but it is presented as static testimonial copy.",
    inference: "A per-property irrigation health view could make savings visible over time for homeowners and HOA boards.",
    offerTitle: "Irrigation health dashboard",
    offerScope: "Zone status, visit history, water-use trend and simple client view.",
    priceRange: "$900–$1,800",
    deliveryTime: "7–10 days",
    previewIdea: "A single property dashboard showing zone health and monthly water trend.",
    subject: "an idea for Mar Lawn's water-savings story",
    emailBody: "Hi Abel,\n\nOne of Mar Lawn's testimonials mentions roughly 30% lower water use after an irrigation upgrade. That is an unusually concrete result.\n\nI built a working concept that makes that result visible per property: zone health, visit history and water savings over time.\n\nIf that would help with HOA or maintenance clients, I can build the real version around your reporting. If not, no worries.\n\nPaul",
    reviewerNote: "Initial email sent.",
    sourceUrls: JSON.stringify(["https://marlandscape.com"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: null,
    nextFollowUpAt: followUp,
  },
  {
    id: "vc-turf",
    businessName: "VC Turf",
    website: "https://vcturf.com",
    location: "Ventura County, CA",
    industry: "Artificial turf & hardscape",
    contactName: "VC Turf team",
    contactRole: "Estimating",
    contactEmail: "info@vcturf.com",
    emailConfidence: "MEDIUM",
    emailSourceUrl: "https://vcturf.com/contact-us",
    fit: "GOOD FIT",
    score: 84,
    status: "sent",
    signalType: "Estimate qualification",
    signalSummary: "Project pricing depends on area, grade, removal, access and installation conditions.",
    observation: "The business publishes enough project information for customers to estimate rough scope.",
    inference: "A guided estimator could filter casual inquiries and give estimators structured information before a visit.",
    offerTitle: "Pre-estimate project calculator",
    offerScope: "Area, material grade, removal, access, photo upload and quote-request handoff.",
    priceRange: "$650–$1,100",
    deliveryTime: "5–7 days",
    previewIdea: "A clickable cost range using the company's published service structure.",
    subject: "made your Project Cost page clickable",
    emailBody: "Hi VC Turf team,\n\nI noticed customers have to understand several variables before a turf estimate is meaningful — area, grade, removal and site access.\n\nI made a small interactive version so a homeowner can build a rough range and send a cleaner project request.\n\nIf useful, I can turn it into a real branded estimator. If not, no problem.\n\nPaul",
    reviewerNote: "Initial email sent.",
    sourceUrls: JSON.stringify(["https://vcturf.com", "https://vcturf.com/contact-us"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: null,
    nextFollowUpAt: followUp,
  },
  {
    id: "greencoast",
    businessName: "GreenCoast Landscapes",
    website: "https://greencoastlandscapes.com",
    location: "Ventura County, CA",
    industry: "Public works landscaping",
    contactName: "Jessica",
    contactRole: "Operations contact",
    contactEmail: "jessica@greencoastlandscapes.com",
    emailConfidence: "MEDIUM",
    emailSourceUrl: "https://ci.san-fernando.ca.us/",
    fit: "BEST FIT",
    score: 89,
    status: "sent",
    signalType: "Public-project compliance",
    signalSummary: "Public infrastructure work creates recurring labor and field-record requirements.",
    observation: "GreenCoast lists work connected to Caltrans, municipalities, schools and flood-control projects.",
    inference: "Crew hours, classifications, photos and notes can feed a weekly compliance workflow.",
    offerTitle: "Field-to-certified-payroll console",
    offerScope: "Mobile daily log, job coding, classifications, exception review and weekly export.",
    priceRange: "$1,200–$3,000",
    deliveryTime: "10–15 days",
    previewIdea: "A Wednesday exception screen showing what is missing before payroll closes.",
    subject: "the Wednesday problem",
    emailBody: "Hi Jessica,\n\nI was looking at GreenCoast's public-project work. On those jobs, the same field day can create hours, classifications, photos, materials and approval records.\n\nI built a small console showing how one crew log can feed the weekly compliance record instead of being reconstructed later.\n\nIf it resembles a real bottleneck, I can build it around your process. If not, all good.\n\nPaul",
    reviewerNote: "Initial email sent.",
    sourceUrls: JSON.stringify(["https://greencoastlandscapes.com"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: null,
    nextFollowUpAt: followUp,
  },
  {
    id: "legacy-tree",
    businessName: "Legacy Tree Care",
    website: "https://www.legacytreecare.net",
    location: "Ventura County, CA",
    industry: "Arborist & tree care",
    contactName: "Legacy Tree Care team",
    contactRole: "Office",
    contactEmail: "info@legacytreecare.net",
    emailConfidence: "MEDIUM",
    emailSourceUrl: "https://www.legacytreecare.net/contact-us",
    fit: "GOOD FIT",
    score: 82,
    status: "sent",
    signalType: "Recurring asset history",
    signalSummary: "Tree inspections and recommendations gain value when preserved across years.",
    observation: "The service produces repeat inspections, pruning history, condition notes and recommendations.",
    inference: "A per-tree history can turn a one-off inventory into a recurring client asset.",
    offerTitle: "Client tree-inventory portal",
    offerScope: "Property map, tree profiles, inspection history, photos and recommended next action.",
    priceRange: "$900–$1,800",
    deliveryTime: "7–12 days",
    previewIdea: "Click one sample tree to see condition history and next recommended action.",
    subject: "between updates",
    emailBody: "Hi Legacy Tree Care team,\n\nA tree inventory becomes more valuable after the first visit, when condition, work and photos can be compared over time.\n\nI built a small portal where a client can click a tree and see its inspection history, photos and next recommended action.\n\nIf it fits the way you deliver inventories, I can build the real version. If not, no problem.\n\nPaul",
    reviewerNote: "Initial email sent.",
    sourceUrls: JSON.stringify(["https://www.legacytreecare.net", "https://www.legacytreecare.net/contact-us"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: null,
    nextFollowUpAt: followUp,
  },
  {
    id: "aguilar-pro",
    businessName: "Aguilar Pro Landscaping",
    website: "https://www.aguilarprolandscapinginc.com",
    location: "Ventura County, CA",
    industry: "Residential landscape services",
    contactName: "Miguel",
    contactRole: "Business contact",
    contactEmail: "aguilarprolandscaping@gmail.com",
    emailConfidence: "MEDIUM",
    emailSourceUrl: "https://www.aguilarprolandscapinginc.com/contact-us",
    fit: "GOOD FIT",
    score: 78,
    status: "sent",
    signalType: "Service complexity",
    signalSummary: "A broad service menu creates different intake questions and recurring schedules.",
    observation: "The company offers maintenance, sprinklers, fences, pavers, turf, cleanups and tree work.",
    inference: "A bilingual intake can route one-time projects and recurring customers into clean queues.",
    offerTitle: "Bilingual recurring-service intake",
    offerScope: "English/Spanish intake, service routing, frequency, day preference and gate notes.",
    priceRange: "$600–$1,000",
    deliveryTime: "5–7 days",
    previewIdea: "A two-language recurring-service booking flow on one screen.",
    subject: "reservar servicio",
    emailBody: "Hi Miguel,\n\nAguilar Pro covers a wide mix of one-time projects and recurring work, so the first questions change with the service.\n\nI built a small English/Spanish intake that routes projects and maintenance separately, including frequency, preferred day and access notes.\n\nIf useful, I can make the real version for your site. If not, no problem.\n\nPaul",
    reviewerNote: "Initial email sent.",
    sourceUrls: JSON.stringify(["https://www.aguilarprolandscapinginc.com"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: null,
    nextFollowUpAt: followUp,
  },
  {
    id: "chilcutt",
    businessName: "Chilcutt Landscape",
    website: "https://chilcuttlandscape.com",
    location: "Ventura County, CA",
    industry: "Landscape construction",
    contactName: "Cole",
    contactRole: "Owner / operator",
    contactEmail: "cole.chilcuttlandscape@gmail.com",
    emailConfidence: "MEDIUM",
    emailSourceUrl: "https://chilcuttlandscape.com",
    fit: "GOOD FIT",
    score: 80,
    status: "sent",
    signalType: "Referral response time",
    signalSummary: "Public recommendations create warm leads that still need fast acknowledgement.",
    observation: "Local customers recommend the business by name and it operates with active crews and equipment.",
    inference: "A tiny callback queue could acknowledge referrals and make waiting time visible.",
    offerTitle: "Referral intake and callback queue",
    offerScope: "Automatic acknowledgement, wait timer and quote/site-visit/not-fit actions.",
    priceRange: "$600–$1,100",
    deliveryTime: "5–7 days",
    previewIdea: "Three referral cards showing time waiting and the next action.",
    subject: "your referrals",
    emailBody: "Hi Cole,\n\nI noticed people around East Ventura recommend Chilcutt by name when someone asks who to call. Those leads arrive warm, but they usually do not wait long.\n\nI built a small callback queue: each lead is acknowledged immediately, shows how long it has waited and has only three next actions.\n\nIf it would help, I can wire the real version to your site and phone. If not, no problem.\n\nPaul",
    reviewerNote: "Initial email sent.",
    sourceUrls: JSON.stringify(["https://chilcuttlandscape.com"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: null,
    nextFollowUpAt: followUp,
  },
  {
    id: "promised-landscape",
    businessName: "The Promised Landscape",
    website: "https://thepromisedlandscape.com",
    location: "Ventura, CA",
    industry: "Landscape contractor",
    contactName: "Scott Yonker",
    contactRole: "Owner",
    contactEmail: "yonks70@msn.com",
    emailConfidence: "HIGH",
    emailSourceUrl: "https://thepromisedlandscape.com/about-us",
    fit: "GOOD FIT",
    score: 81,
    status: "sent",
    signalType: "Visible waitlist",
    signalSummary: "The company deliberately runs one project at a time and depends on referrals.",
    observation: "The owner publicly emphasizes undivided attention and one-job-at-a-time delivery.",
    inference: "A simple queue can keep referred clients informed without changing how the company works.",
    offerTitle: "Client place-in-line page",
    offerScope: "Current project, queue position, approximate start window and short updates.",
    priceRange: "$500–$900",
    deliveryTime: "4–6 days",
    previewIdea: "A referred-client view showing queue position without exposing private details.",
    subject: "your place in line",
    emailBody: "Hi Scott,\n\nI read the part of your site about doing one job at a time so each project gets your undivided attention. The one cost of that promise is that referred clients sometimes have to wait.\n\nI built a simple page they could check: what is in progress, where they stand and a rough start window. Nothing changes about how you work; the wait just becomes visible.\n\nIf it fits, I can build the real one. If it does not, no problem.\n\nPaul",
    reviewerNote: "Initial email sent.",
    sourceUrls: JSON.stringify(["https://thepromisedlandscape.com", "https://thepromisedlandscape.com/about-us"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: null,
    nextFollowUpAt: followUp,
  },
  {
    id: "plant-persuasion",
    businessName: "Plant Persuasion",
    website: "https://www.plantpersuasion.com",
    location: "Ventura County, CA",
    industry: "Estate landscape design",
    contactName: "Plant Persuasion team",
    contactRole: "Design studio",
    contactEmail: "PlantPersuasion@Peoplepc.com",
    emailConfidence: "MEDIUM",
    emailSourceUrl: "https://www.plantpersuasion.com",
    fit: "GOOD FIT",
    score: 76,
    status: "review",
    signalType: "Portfolio presentation",
    signalSummary: "The site has a detailed intake process; project presentation can do more trust-building.",
    observation: "The business serves design-led estate clients and already asks thoughtful questions before a consultation.",
    inference: "The strongest opportunity may be a structured project-story system rather than another intake form.",
    offerTitle: "Estate project story system",
    offerScope: "Project brief, plant palette, water approach, before/after and consultation handoff.",
    priceRange: "$650–$1,200",
    deliveryTime: "5–8 days",
    previewIdea: "One polished sample project story using clearly marked illustrative content.",
    subject: "an idea for presenting estate projects",
    emailBody: "Hi Plant Persuasion team,\n\nI spent some time with your intake process. It already asks the kinds of questions that separate a serious estate project from a casual inquiry.\n\nThe opportunity I see is after that: turning each finished project into a clear story — the brief, plant palette, water approach, before and after, and specification — so the portfolio does more trust-building before a consultation.\n\nI made a small illustrative concept. If the direction is useful, I can build it around your real work. If not, all good.\n\nPaul\n\nP.S. If you would rather I do not follow up, reply no and I will not.",
    reviewerNote: "Review the framing before sending. Avoid presenting a website flaw as the opening angle.",
    sourceUrls: JSON.stringify(["https://www.plantpersuasion.com"]),
    approvedAt: null,
    sentAt: null,
    repliedAt: null,
    nextFollowUpAt: null,
  },
  {
    id: "organic-greens",
    businessName: "Organic Greens Landscapes",
    website: "https://www.organicgreenslandscape.com",
    location: "Ventura County, CA",
    industry: "Landscape maintenance",
    contactName: "RJ",
    contactRole: "Business contact",
    contactEmail: "rj@organicgreenslandscapes.com",
    emailConfidence: "LOW",
    emailSourceUrl: "https://www.organicgreenslandscape.com",
    fit: "EXPERIMENT",
    score: 61,
    status: "sent",
    signalType: "Recurring route operations",
    signalSummary: "Recurring service creates the same property information on every visit.",
    observation: "The business offers recurring maintenance and receives homeowner and contractor inquiries.",
    inference: "A phone-first route checklist could build property history without repeated office re-entry.",
    offerTitle: "Route and property history tool",
    offerScope: "Daily route, property checklist, issue photos and visit history.",
    priceRange: "$750–$1,400",
    deliveryTime: "7–10 days",
    previewIdea: "A phone route with three properties and one issue flowing to the office.",
    subject: "your contact path",
    emailBody: "Hi RJ,\n\nRecurring maintenance creates the same basic information on every visit — what was done, what changed and what needs attention next.\n\nI built a small phone workflow where the route, property checklist, issue photos and history stay together instead of being reconstructed afterward.\n\nIf it resembles something useful, I can build the real version around your routes. If not, no problem.\n\nPaul",
    reviewerNote: "Sent by owner decision even though the published email domain did not exactly match the website domain.",
    sourceUrls: JSON.stringify(["https://www.organicgreenslandscape.com"]),
    approvedAt: sent,
    sentAt: sent,
    repliedAt: null,
    nextFollowUpAt: followUp,
  },
];
